var Acrobacia = Destreza
var Arte = Inteligência
var Atletismo = Força
var CiênciasNaturais = Inteligência
var Concentração = Inteligência
var Cultura = Inteligência
var Disfarces = Percepção
var Escapar = Destreza
var Furtividade = Agilidade
var LidarComAnimais = Percepção
var Mecanismos = Inteligência
var Medicina = Inteligência
var Ocultismo = Inteligência
var Prestidigitação = Destreza
var Procurar = Percepção
var Prontidão = Percepção
var Rastrear = Percepção
var Venéficio = Inteligência

var Iniciativa = Prontidão + Agilidade

document.getElementById("Acrobacia").textContent = Acrobacia;
document.getElementById("Arte").textContent = Arte;
document.getElementById("Atletismo").textContent = Atletismo;
document.getElementById("CiênciasNaturais").textContent = CiênciasNaturais;
document.getElementById("Concentração").textContent = Concentração;
document.getElementById("Cultura").textContent = Cultura;
document.getElementById("Disfarces").textContent = Disfarces;
document.getElementById("Escapar").textContent = Escapar;
document.getElementById("Furtividade").textContent = Furtividade;
document.getElementById("LidarComAnimais").textContent = LidarComAnimais;
document.getElementById("Mecanismos").textContent = Mecanismos;
document.getElementById("Medicina").textContent = Medicina;
document.getElementById("Ocultismo").textContent = Ocultismo;
document.getElementById("Prestidigitação").textContent = Prestidigitação;
document.getElementById("Procurar").textContent = Procurar;
document.getElementById("Prontidão").textContent = Prontidão;
document.getElementById("Rastrear").textContent = Rastrear;
document.getElementById("Venéficio").textContent = Venéficio;
document.getElementById("Iniciativa").textContent = Iniciativa
